# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- powershell: |
    Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-infra/depot_tools.zip" -OutFile depot_tools.zip
    &7z x depot_tools.zip -odepot_tools
    Remove-Item depot_tools.zip
  displayName: 'Fetch depot_tools'
  
- script: |
    set PATH=%PATH%;%cd%\depot_tools;
    cd depot_tools
    gclient
  displayName: 'Config depot_tools'
  
- script: |
    set PATH=%PATH%;%cd%\depot_tools;
    fetch skia
    cd skia
    python2 tools\git-sync-deps
  displayName: 'Setup skia repo'

- powershell: |
    cd skia
    bin/gn gen out/Shared_32_static_vs --args='is_official_build=true is_component_build=false target_os=\"win\" skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_icu=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false extra_cflags=[  \"/EHsc\", \"/Z7\" , \"/wd4291\"  ] extra_ldflags=[ \"/DEBUG:FULL\" ] target_cpu=\"x32\"' --ide=vs
    bin/gn gen out/Shared_64_static_vs --args='is_official_build=true is_component_build=false target_os=\"win\" skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_icu=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false extra_cflags=[  \"/EHsc\", \"/Z7\" , \"/wd4291\"  ] extra_ldflags=[ \"/DEBUG:FULL\" ] target_cpu=\"x64\"' --ide=vs
  displayName: 'Setup build projects'

- script: |
    cd skia
    cd out\Shared_64_static_vs
    msbuild all.sln
  displayName: 'Build skia'

