# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- powershell: |
    Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-infra/depot_tools.zip" -OutFile depot_tools.zip
    &7z x depot_tools.zip -odepot_tools
    Remove-Item depot_tools.zip
  displayName: 'Fetch depot_tools'
  
- script: |
    set PATH=%cd%\depot_tools;%PATH%;
    cd depot_tools
    gclient
  displayName: 'Config depot_tools'
  
- script: |
    set PATH=%cd%\depot_tools;%PATH%;
    fetch skia
  displayName: 'Fetch skia repo'

- script: |
    set PATH=%cd%\depot_tools;%PATH%;
    cd skia
    ..\depot_tools\python tools\git-sync-deps
  displayName: 'Sync skia deps'
  
- powershell: |
    choco install llvm
    $env:Path = "$pwd\depot_tools;" + $env:Path
    cd skia
    bin/gn gen out/Shared_32_static_vs --args='clang_win=\"C:\Program Files\LLVM\" is_official_build=true is_component_build=true target_os=\"win\" skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_icu=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false extra_cflags=[  \"/EHsc\", \"/Z7\" , \"/wd4291\"  ] extra_ldflags=[ \"/DEBUG:FULL\" ] target_cpu=\"x32\"' --ide=vs
    bin/gn gen out/Shared_64_static_vs --args='clang_win=\"C:\Program Files\LLVM\" is_official_build=true is_component_build=true target_os=\"win\" skia_use_system_expat=false skia_use_system_libjpeg_turbo=false skia_use_system_icu=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false extra_cflags=[  \"/EHsc\", \"/Z7\" , \"/wd4291\"  ] extra_ldflags=[ \"/DEBUG:FULL\" ] target_cpu=\"x64\"' --ide=vs
  displayName: 'Setup build projects'

- script: |
    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
    cd skia
    cd out\Shared_64_static_vs
    msbuild all.sln /t:skia
  displayName: 'Build skia'

